---

- name: Add key for nginx repo
  apt_key:
    url: 'http://nginx.org/keys/nginx_signing.key'
    state: present

- name: Add nginx repo
  apt_repository:
    repo: 'deb http://nginx.org/packages/ubuntu/ trusty nginx'
    state: present
    update_cache: yes

- name: Install package
  apt:
    name: nginx
    state: installed

- name: Run and enable Nginx to start on boot
  service:
    name: nginx
    state: started
    enabled: yes

